TOP=../..
include $(TOP)/configure/CONFIG

#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE


ABC += file01.ABC file02.ABC



include $(TOP)/configure/RULES

#----------------------------------------
#  ADD RULES AFTER THIS LINE

